"""Render a hybrid code Review to the terminal or to GitHub markdown."""
from __future__ import annotations

from typing import List

from .review import Review, ReviewComment
from .util import C, SEV_RANK

SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}
SEV_COLOR = {"critical": C.red, "high": C.red, "medium": C.yellow,
             "low": C.blue, "info": C.dim}


VERDICT_TERMINAL = {
    "approve": lambda m: C.green("✅ Approve — ") + m,
    "request_changes": lambda m: C.red("🔧 Changes requested — ") + m,
    "comment": lambda m: C.yellow("💬 Comment — ") + m,
}
VERDICT_MD = {
    "approve": "✅ **Approve** — ",
    "request_changes": "🔧 **Changes requested** — ",
    "comment": "💬 **Comment** — ",
}


def _counts(comments: List[ReviewComment]):
    out = {}
    for c in comments:
        out[c.severity] = out.get(c.severity, 0) + 1
    return out


# --------------------------------------------------------------------------- #
def render_terminal(review: Review) -> None:
    print(C.bold("\n🦓 Zebra code review"))
    if review.model:
        print(C.dim(f"   engine: deterministic scanners + {review.model}"))
    if review.llm_status:
        print(f"   {C.yellow('LLM pass skipped')}: {C.dim(review.llm_status)}")
    print()

    # verdict banner — the headline answer: good to merge, or change something?
    if review.verdict_message:
        line = VERDICT_TERMINAL.get(review.verdict_decision,
                                    VERDICT_TERMINAL["comment"])(review.verdict_message)
        print(C.bold(line) + "\n")

    if review.overview_summary:
        print(C.bold("Overview"))
        print(f"  {review.overview_summary}\n")

    if review.file_descriptions:
        print(C.bold("Files"))
        for path, desc in review.file_descriptions:
            print(f"  {C.cyan(path)}")
            print(f"    {C.dim(desc)}")
        print()
    elif review.changed_files:
        print(C.bold("Files changed"))
        for f in review.changed_files:
            print(f"  {C.cyan(f.path)} {C.dim('(' + f.status + ')')}")
        print()

    if not review.comments:
        print(C.green("  No review comments. 👍\n"))
        return

    counts = _counts(review.comments)
    summary = "  ".join(SEV_COLOR.get(s, C.dim)(f"{s}:{n}")
                        for s, n in sorted(counts.items(),
                                           key=lambda kv: SEV_RANK.get(kv[0], 99)))
    print(C.bold(f"Comments ({len(review.comments)})  {summary}\n"))

    for path, group in review.by_file().items():
        print(C.bold(C.cyan(f"▌ {path}")))
        for c in group:
            sev = SEV_COLOR.get(c.severity, C.dim)(f"{c.severity:<8}")
            tag = C.dim(f"[{c.source}{('/' + c.confidence) if c.confidence else ''}]")
            print(f"   {sev} line {c.line}  {tag}")
            print(f"            {c.body}")
            if c.suggestion:
                print(f"            {C.green('suggested fix:')} {c.suggestion}")
        print()


# --------------------------------------------------------------------------- #
def render_markdown(review: Review, inline_suggestions: bool = True) -> str:
    lines = ["## 🦓 Zebra code review", ""]
    if review.verdict_message:
        lines += [VERDICT_MD.get(review.verdict_decision,
                                 VERDICT_MD["comment"]) + review.verdict_message, ""]
    if review.overview_summary:
        lines += ["### Pull request overview", "", review.overview_summary, ""]
    if review.file_descriptions:
        lines += ["| File | Description |", "| --- | --- |"]
        for path, desc in review.file_descriptions:
            lines.append(f"| `{path}` | {desc.replace('|', chr(92) + '|')} |")
        lines.append("")

    if not review.comments:
        lines += ["_No review comments._", ""]
    else:
        lines += [f"### Comments ({len(review.comments)})", ""]
        for path, group in review.by_file().items():
            lines += [f"#### `{path}`", ""]
            for c in group:
                emoji = SEV_EMOJI.get(c.severity, "")
                meta = f"{emoji} **{c.severity}**"
                if c.confidence:
                    meta += f" · {c.confidence} confidence"
                meta += f" · `{c.source}`"
                lines.append(f"- **L{c.line}** — {meta}  ")
                lines.append(f"  {c.body}")
                if c.suggestion and inline_suggestions:
                    lines.append("")
                    lines.append("  ```suggestion")
                    lines.append("  " + c.suggestion)
                    lines.append("  ```")
            lines.append("")

    if review.llm_status:
        lines += [f"> _LLM pass skipped: {review.llm_status}_", ""]
    if review.model and not review.llm_status:
        lines += [f"<sub>🦓 Generated by Zebra · {review.model} + deterministic "
                  f"scanners</sub>"]
    return "\n".join(lines)
